### ISSUE TITLE
Problems verifying the trust relationship between a digital signer and a supplier of a digitally signed object

### ISSUE THREAD

**Issue by rjb4standards** [ietf-rats/draft-birkholz-rats-epoch-marker#3]
this information is contained in two articles on Energy Central, but I'll summarize here.
https://energycentral.com/c/ec/we-cannot-secure-software-supply-chain-without-sbom 
https://energycentral.com/c/ec/who-ya-gonna-trust 

Today's digital signing methods allow anyone with a valid signing certificate/key to sign any object, without requiring authorization from the party that originated the artifact. Software consumers have no way to "validate" that a digitally signed object, i.e., Program A produced by supplier S that is signed using a certificate owned by party D is legitimate. Software consumers that need to establish trust in Program A need a reliable method to confirm that Supplier S authorized signer D to sign Program A as part of digital signature verification during a software supply chain risk assessment.  

Current digital signature verification practices only check that the signers certificate is valid and the MAC in the signature matches the computed hash of the signed artifact i.e. Program A (integrity verification), but does not provide any assurance as to the trustworthiness of the relationship between a signer in the digital signature and the supplier of an artifact. Anyone can sign anything today, without authorization from the originator of an artifact and the digital signature verification check will pass.

**Comment by henkbirkholz** [comment]
The Epoch Bell must be endorsed. There is the option to add veracity proofs to Epoch Markers so that policies can decide, if the singer of Epoch Markers (the Epoch Bell system & the Epoch Bell Owner) is trustworthy. Currently, the options are to include raw remote Evidence, refined Attestation Result, or slick new SCITT Receipts (that could be Endorsements, such as NIST 3rd Party Attestations -- never to be confused with actual Remote Attestation!).

Ia that set of options addressing this issues?

**Comment by henkbirkholz** [comment]
Assuming this addresses the issue. Closing for can. Feel free to reopen as a working group item.
